controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        mySprite.vy += -200
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    info.changeScoreBy(1)
})
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
controller.moveSprite(mySprite, 100, 0)
scene.cameraFollowSprite(mySprite)
mySprite = sprites.create(img`
    ........ccc.............
    ........cccccccc........
    .....cc..cc55555cc......
    .....cccc555555555c.....
    .....ccb55555555555c....
    ...cc.b5555bcc555555c...
    ...ccb55555555c55d55c...
    ....cb5555dd55555555c...
    .....5555dd5555d5555c...
    ..cc.555dd555555dbbbc...
    ..ccc55ddd555555d555c...
    ...ccd5dbdd5555d555c....
    ....bdddb555bbbbbccc....
    ..cccdddb555cbbbbbbbc...
    ...ccddddb555cbbbbbbbc..
    ....cdddddb555cbbbbbbc..
    ...ccddddddb55cbbbbbbcc.
    ...cbddddd55bcbbbbbbbcc.
    ..cbdddddd5555bbbbbbbc..
    .cddddddbdd555bbbbbbc...
    cddddddbbbdd55cbbccc....
    ccccccbbcbddddccdddcc...
    ......cccdd555dcccccc...
    ........cccccccc........
    `, SpriteKind.Player)
mySprite.setStayInScreen(true)
let Mat = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ............eee.................
    ...........e562e................
    .........4744776778.............
    ........5377226ee88.............
    .......474675d55ddd.............
    ......e54f5d55555dd.............
    .....e54ffd555555dd.............
    .....e5ffe55555de...............
    .....e5ef55545de................
    ......e4e545e...................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Food)
info.setLife(3)
info.setScore(0)
