controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 3 3 4 4 . . . . . . 
        . . . . . . 3 2 2 5 . . . . . . 
        . . . . . . 3 2 4 4 . . . . . . 
        . . . . . . 4 2 2 4 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, 0, 50)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite)
    info.changeLifeBy(-1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(sprite)
    sprites.destroy(otherSprite, effects.confetti, 100)
    info.changeScoreBy(1)
})
let Hai: Sprite = null
let projectile: Sprite = null
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    ........ccc.............
    ........cccccccc........
    .....cc..cc55555cc......
    .....cccc555555555c.....
    .....ccb55555555555c....
    ...cc.b5555bcc555555c...
    ...ccb55555555c55d55c...
    ....cb5555dd55555555c...
    .....5555dd5555d5555c...
    ..cc.555dd555555dbbbc...
    ..ccc55ddd555555d555c...
    ...ccd5dbdd5555d555c....
    ....bdddb555bbbbbccc....
    ..cccdddb555cbbbbbbbc...
    ...ccddddb555cbbbbbbbc..
    ....cdddddb555cbbbbbbc..
    ...ccddddddb55cbbbbbbcc.
    ...cbddddd55bcbbbbbbbcc.
    ..cbdddddd5555bbbbbbbc..
    .cddddddbdd555bbbbbbc...
    cddddddbbbdd55cbbccc....
    ccccccbbcbddddccdddcc...
    ......cccdd555dcccccc...
    ........cccccccc........
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 50, 100)
mySprite.setPosition(26, 12)
mySprite.setStayInScreen(true)
let Mat = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ............eee.................
    ...........e562e................
    .........4744776778.............
    ........5377226ee88.............
    .......474675d55ddd.............
    ......e54f5d55555dd.............
    .....e54ffd555555dd.............
    .....e5ffe55555de...............
    .....e5ef55545de................
    ......e4e545e...................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Food)
Mat.setPosition(scene.screenWidth() * 0.9, scene.screenHeight() * 0.5)
scene.cameraFollowSprite(mySprite)
info.setLife(3)
info.setScore(0)
game.onUpdateInterval(1000, function () {
    Hai = sprites.create(img`
        ...........fffffff...ccfff..........
        ..........fbbbbbbbffcbbbbf..........
        ..........fbb111bbbbbffbf...........
        ..........fb11111ffbbbbff...........
        ..........f1cccc1ffbbbbbcff.........
        ..........ffc1c1c1bbcbcbcccf........
        ...........fcc3331bbbcbcbcccf..ccccc
        ............c333c1bbbcbcbccccfcddbbc
        ............c333c1bbbbbbbcccccddbcc.
        ............c333c11bbbbbccccccbbcc..
        ...........cc331c11bbbbccccccfbccf..
        ...........cc13c11cbbbcccccbbcfccf..
        ...........c111111cbbbfdddddc.fbbcf.
        ............cc1111fbdbbfdddc...fbbf.
        ..............cccfffbdbbfcc.....fbbf
        ....................fffff........fff
        `, SpriteKind.Enemy)
    Hai.setPosition(randint(0, scene.screenWidth()), scene.screenHeight())
    Hai.setVelocity(0, -50)
    Hai.setFlag(SpriteFlag.DestroyOnWall, true)
})
